description: |
  The Orb-Tools orb is typically configured automatically by the Orb Development Kit. After initializing a new orb, this is the configuration file that will be automatically loaded.
  This configuration uses "Dynamic Config" with two different configuration files, so here we will see only the first `config.yml` file.
  This config breaks our orb's CI pipeline into two workflows, "test-pack", and "test-deploy".
  "test-pack" will lint, shellcheck, and review our orb, before publishing a new development version of the orb and triggering the "test-deploy" workflow.
  See the list of jobs for a detailed description of each job.
  "test-deploy" deploy is found in the `./circleci/test-deploy.yml` file. See step 2 for more information.
version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@11.1
  shellcheck: circleci/shellcheck@3.1

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      # - orb-tools/review:
      #     filters: *filters
      - shellcheck/check:
          filters: *filters
      - orb-tools/publish:
          orb-name: redventures/wiz
          vcs-type: << pipeline.project.type >>
          requires:
            [orb-tools/lint, orb-tools/pack, shellcheck/check]
          # Use a context to hold your publishing token.
          context: 
            - orb-publishing
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline-number: << pipeline.number >>
          vcs-type: << pipeline.project.type >>
          requires: [orb-tools/publish]
          filters: *filters
